#!/usr/bin/env bash
#
# Build HORNOFINO for a real iPhone or for the Simulator, and install it.
#
#   scripts/build-ios.sh device   # Release, signed, installed over devicectl
#   scripts/build-ios.sh sim      # Release, unsigned, installed on a booted sim
#   scripts/build-ios.sh archive  # Release, distribution-signed, exported .ipa
#
# `device` is the WIRELESS path: devicectl reaches the phone over its own
# network tunnel, so no cable is involved. What it ships is a whole new
# binary, not a patch — this app has no expo-updates and no EAS project, so
# there is no over-the-air JS update to send. Every change, however small,
# is a full build. Budget ~30 minutes, not seconds.
#
# `archive` stops at the .ipa. It does NOT upload — that needs App Store
# Connect credentials, so the last leg is yours: Xcode Organizer, or
# `xcrun altool`/`notarytool` with an ASC API key.
#
# Ported from drinkdex (Sipply) scripts/build-ios.sh, where each of the
# lessons below cost a failed build to learn:
#
#  1. LANG. CocoaPods calls String#unicode_normalize, which raises
#     "Unicode Normalization not appropriate for ASCII-8BIT" when the shell
#     has no UTF-8 locale. Non-login shells here have LANG unset and
#     LC_CTYPE=C, so `pod install` dies inside `expo prebuild`.
#
#  2. DEVELOPMENT_TEAM is NOT in app.json, and `ios/` is gitignored and
#     regenerated by prebuild — so a `prebuild --clean` wipes the team and
#     the next build fails with "Signing for HORNOFINO requires a development
#     team." It is read from ExportOptions.plist at the repo root, which is
#     tracked precisely because it has to survive a prebuild.
#
#  3. NEVER `-destination "id=<device-udid>"`. xcodebuild resolves that
#     through Xcode's device list, which reports the phone offline whenever
#     it has not been plugged in and unlocked recently — and then fails with
#     "Timed out waiting for all destinations". devicectl reaches the same
#     phone over its own tunnel, so build for a GENERIC device and let
#     devicectl do the install.
#
#  4. Release, always. A Debug build has no bundled JS and needs Metro on
#     this Mac, so it dies the moment the phone leaves the desk.
#
# IF THE INSTALL FAILS, DO NOT REBUILD. The build and the install are
# separate legs and they fail for unrelated reasons. A dropped tunnel looks
# nothing like a bad build:
#
#     ** BUILD SUCCEEDED **
#     ERROR: A connection to this device could not be established.
#            CoreDeviceError 4000 / NWError 54 — connection reset by peer
#
# That is half an hour of good work sitting on disk behind a transient
# network error. Check the artifact and rerun the install alone:
#
#     ls -l ios/build/Build/Products/Release-iphoneos/HORNOFINO.app/HORNOFINO
#     xcrun devicectl device install app --device <UDID> <path>/HORNOFINO.app
#
# Install failures worth recognising: kAMDMobileImageMounterDeviceLocked
# means unlock the phone (iOS will not mount the developer disk image until
# the handset has been unlocked once since boot) — a hardware state,
# correctly reported, not a bug.
#
# CONCURRENCY. Xcode's build lock lives at
# node_modules/.../XCBuildData/build.db, INSIDE node_modules, so a separate
# -derivedDataPath does not isolate it. This repo has its own node_modules,
# so it does NOT share drinkdex's lock — but it does share the CPU, and a
# Release build here runs the machine hot enough to stall one there. The
# pgrep guard below only catches builds of THIS app; announce cross-repo
# builds to peer sessions yourself.

set -euo pipefail

MODE="${1:-device}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

if pgrep -f "xcodebuild.*HORNOFINO" >/dev/null 2>&1; then
  echo "Another xcodebuild is already running against this repo. Wait for it." >&2
  exit 1
fi

TEAM="$(/usr/libexec/PlistBuddy -c 'Print :teamID' ExportOptions.plist)"

if [ ! -d ios ]; then
  echo "==> ios/ is missing; running prebuild"
  npx expo prebuild -p ios
fi

case "$MODE" in
  device)
    echo "==> Building Release for a generic iOS device (team $TEAM)"
    xcodebuild -workspace ios/HORNOFINO.xcworkspace -scheme HORNOFINO \
      -configuration Release -destination 'generic/platform=iOS' \
      -allowProvisioningUpdates -derivedDataPath ios/build \
      DEVELOPMENT_TEAM="$TEAM" CODE_SIGN_STYLE=Automatic build

    APP="ios/build/Build/Products/Release-iphoneos/HORNOFINO.app"
    # A killed build leaves a hollow bundle rather than no bundle at all.
    [ -s "$APP/HORNOFINO" ] || { echo "No binary in $APP — build did not finish." >&2; exit 1; }

    # Match the UDID by SHAPE, never by field position. devicectl's columns
    # are whitespace-separated but two of them hold variable-length names:
    # the device name ("MC iPhone") and the model ("iPhone 17 Pro Max"). A
    # positional $(NF-3) returns "17" — a number out of the model name — and
    # devicectl then fails with 'device was not found (Name: 17)', which
    # reads like a build bug when the build was fine.
    #
    # devicectl reports TWO installable states and the pattern must accept
    # both: "available (paired)" when the phone is idle, and "connected"
    # when it is actively tunnelled. "unavailable" must NOT match, which is
    # why the first alternative keeps "(paired)" rather than testing for
    # "available" alone; "disconnected" is excluded by the word boundary.
    DEV="$(xcrun devicectl list devices 2>/dev/null \
           | awk '/available \(paired\)|(^| )connected( |$)/ {
                    for (i = 1; i <= NF; i++)
                      if ($i ~ /^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$/) {
                        print $i; exit
                      }
                  }')"
    [ -n "$DEV" ] || {
      echo "No installable device. Unlock the phone, put it on this network," >&2
      echo "and trust this Mac. The .app is already built and fine — rerun" >&2
      echo "the install alone rather than rebuilding (see header)." >&2
      echo "What devicectl can see:" >&2
      xcrun devicectl list devices >&2 2>/dev/null
      exit 1
    }

    echo "==> Installing to $DEV"
    # `install`, not `launch`: devicectl installs onto a locked phone, which
    # is why this is the reliable path. Tap the icon yourself.
    xcrun devicectl device install app --device "$DEV" "$APP"
    ;;

  sim)
    UDID="$(xcrun simctl list devices booted -j \
            | python3 -c 'import json,sys; d=json.load(sys.stdin)["devices"]; print(next((x["udid"] for v in d.values() for x in v), ""))')"
    [ -n "$UDID" ] || { echo "No booted simulator. Boot one first." >&2; exit 1; }

    echo "==> Building Release for simulator $UDID"
    xcodebuild -workspace ios/HORNOFINO.xcworkspace -scheme HORNOFINO \
      -configuration Release -destination "platform=iOS Simulator,id=$UDID" \
      -derivedDataPath ios/build-sim CODE_SIGNING_ALLOWED=NO build

    APP="ios/build-sim/Build/Products/Release-iphonesimulator/HORNOFINO.app"
    xcrun simctl install "$UDID" "$APP"
    xcrun simctl launch "$UDID" com.mcqueenygroup.hornofino
    ;;

  archive)
    # Everything in `device` applies here too — the LANG export, the team read
    # out of ExportOptions.plist, and the generic destination. Three things are
    # different, and each is the kind of detail that costs a whole build:
    #
    #  1. ARCHIVE STRAIGHT INTO THE ORGANIZER'S FOLDER. Organizer only lists
    #     archives under ~/Library/Developer/Xcode/Archives/<date>/. An archive
    #     written anywhere else is invisible to it, and since Organizer is the
    #     upload path, an archive it cannot see may as well not exist.
    #
    #  2. -allowProvisioningUpdates ON BOTH LEGS. ExportOptions.plist asks for
    #     automatic signing, and the DEVELOPMENT profile that `device` builds
    #     with is not valid for distribution. Xcode has to mint a distribution
    #     profile, and it will only do that with this flag — on the export as
    #     well as the archive, because export re-signs.
    #
    #  3. A SEPARATE derivedDataPath. Sharing ios/build with `device` means a
    #     distribution-signed archive and a development-signed .app fighting
    #     over the same intermediates.
    #
    # BEFORE YOU UPLOAD, two things this script cannot check for you:
    #   - ios/HORNOFINO/HORNOFINO.entitlements ships aps-environment
    #     = development, which is right for `expo run:ios` and WRONG for
    #     TestFlight: push goes to the sandbox and never arrives. Flip it to
    #     production for a distribution build.
    #   - app.json has no ios.config.usesNonExemptEncryption. App Store
    #     Connect will ask about encryption on every upload until it does.
    VERSION="$(node -p "require('$ROOT/app.json').expo.version")"
    BUILD="$(node -p "require('$ROOT/app.json').expo.ios.buildNumber")"

    STAMP="$(date '+%Y-%m-%d')"
    ARCHIVE_DIR="$HOME/Library/Developer/Xcode/Archives/$STAMP"
    ARCHIVE="$ARCHIVE_DIR/HORNOFINO $VERSION ($BUILD) $(date '+%H.%M').xcarchive"
    EXPORT_DIR="$ROOT/ios/build-archive/export"

    mkdir -p "$ARCHIVE_DIR"

    echo "==> Archiving HORNOFINO $VERSION ($BUILD) for the App Store (team $TEAM)"
    echo "    If TestFlight already holds build $BUILD, stop now and bump"
    echo "    ios.buildNumber in app.json — the upload will be refused."

    xcodebuild -workspace ios/HORNOFINO.xcworkspace -scheme HORNOFINO \
      -configuration Release -destination 'generic/platform=iOS' \
      -allowProvisioningUpdates -derivedDataPath ios/build-archive \
      -archivePath "$ARCHIVE" \
      DEVELOPMENT_TEAM="$TEAM" CODE_SIGN_STYLE=Automatic archive

    # Same lesson as the device leg: a killed build leaves a stump, not
    # nothing. An .xcarchive with no binary inside it still looks like a
    # directory that exists.
    [ -s "$ARCHIVE/Products/Applications/HORNOFINO.app/HORNOFINO" ] || {
      echo "No binary inside $ARCHIVE — the archive did not finish." >&2
      exit 1
    }

    echo "==> Exporting .ipa"
    rm -rf "$EXPORT_DIR"
    xcodebuild -exportArchive -archivePath "$ARCHIVE" \
      -exportOptionsPlist ExportOptions.plist \
      -exportPath "$EXPORT_DIR" \
      -allowProvisioningUpdates

    IPA="$(find "$EXPORT_DIR" -maxdepth 1 -name '*.ipa' | head -1)"
    [ -n "$IPA" ] || { echo "Export produced no .ipa. Read the log above." >&2; exit 1; }

    echo
    echo "==> Done. HORNOFINO $VERSION ($BUILD)"
    echo "    Archive: $ARCHIVE"
    echo "    IPA:     $IPA"
    echo
    echo "    Upload is not automated — it needs App Store Connect credentials."
    echo "    Xcode > Window > Organizer will list the archive above; or use an"
    echo "    ASC API key with xcrun altool."
    ;;

  *)
    echo "Usage: scripts/build-ios.sh [device|sim|archive]" >&2
    exit 1
    ;;
esac
